[package]
name = "ailist"
version = "0.1.0"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"
rand = "0.7"

[[bench]]
name = "ailist_benchmarks"
harness = false
